modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/yungnickyoung/Travelers-Titles"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="${mod_credits}"
    authors="YUNGNICKYOUNG"
    description="${mod_description}"
    logoFile="icon.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/travelers-titles"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},1.22)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${mc_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"