modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/yungnickyoung/Travelers-Titles"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="${mod_credits}"
    authors="YUNGNICKYOUNG"
    description="${mod_description}"
    logoFile="icon.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/travelers-titles-neoforge"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${mc_version_range}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${mc_version}-NeoForge-${yungsapi_version},)"
    type="required"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "${mod_id}.mixins.json"
